sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lahtim007/repotest -f Dockerfile.dev .

script:
  - docker run -e CI=true lahtim007/repotest npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ca-central-1-876411132959'
  bucket_path: 'docker-react'
  #preciser la branche qui doit deployer sur aws
  on:
    # specifier la cle et l'acces
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"